import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';
import { getAI, VertexAIBackend } from 'firebase/ai';

const firebaseConfig = {
  "projectId": "ai-logic-demos",
  "appId": "1:861083271982:web:8128d34be86880bdeeb0bf",
  "storageBucket": "ai-logic-demos.firebasestorage.app",
  "apiKey": "AIzaSyAyfIbcQZ8ufeK8WrgwIuiRhEv-1AvjNrI",
  "authDomain": "ai-logic-demos.firebaseapp.com",
  "messagingSenderId": "861083271982",
  "measurementId": "G-1QFETFNRLC",
  "projectNumber": "861083271982",
  "version": "2"
};

import { initializeAppCheck, ReCaptchaEnterpriseProvider } from 'firebase/app-check';

export const app = initializeApp(firebaseConfig);

// Initialize App Check
// For local development, register the debug token generated by setup_appcheck_debug.sh in the Firebase Console.
if (location.hostname === 'localhost' || location.hostname === '127.0.0.1') {
  (self as any).FIREBASE_APPCHECK_DEBUG_TOKEN = "283506C0-51BB-4F2D-83BE-4684B26E5267";
}

initializeAppCheck(app, {
  provider: new ReCaptchaEnterpriseProvider('YOUR_RECAPTCHA_ENTERPRISE_SITE_KEY'),
  isTokenAutoRefreshEnabled: true
});

export const auth = getAuth(app);
export const firestore = getFirestore(app);
export const storage = getStorage(app);
export const ai = getAI(app, { backend: new VertexAIBackend("global") });
